
import os
from utils.data_preprocessing.extract_partially_annotated_dataset import extract_partially_annotated_dataset
from utils.data_preprocessing.load_dr_samples import load_dr_data_from_csv
from utils.populate_dr_predictions_for_dr_sample import populate_dr_predictions_for_dr_samples
from evaluation.evaluate_DR_parser import evaluate_DR_parser_with_f1

# extract_partially_annotated_dataset()
# done


load_dr_data_from_csv()

populate_dr_predictions_for_dr_samples('prompt_2')
evaluate_DR_parser_with_f1()
